/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Initialise le cookie XSRF-TOKEN */
        get: operations["getCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Créer un compte */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Se connecter */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Se déconnecter */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mot de passe oublié */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Réinitialiser le mot de passe */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/handle-availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disponibilité d'un handle */
        get: operations["checkHandle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Utilisateur courant */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /** Suppression du compte (loi 2008-12) — anonymise les commandes, supprime le reste */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lire le profil */
        get: operations["getProfile"];
        /** Modifier le profil */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/socials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lire les réseaux */
        get: operations["getSocials"];
        /** Remplacer les réseaux */
        put: operations["updateSocials"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lire les stats */
        get: operations["getStats"];
        /** Modifier les stats */
        put: operations["updateStats"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page construite à partir du brouillon (aperçu éditeur) */
        get: operations["getPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les blocs */
        get: operations["listBlocks"];
        put?: never;
        /** Créer un bloc */
        post: operations["createBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/blocks/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Réordonner les blocs */
        put: operations["reorderBlocks"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/blocks/{blockId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Modifier un bloc */
        put: operations["updateBlock"];
        post?: never;
        /** Supprimer un bloc */
        delete: operations["deleteBlock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/blocks/{blockId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        /** Lister les éléments */
        get: operations["listBlockItems"];
        put?: never;
        /** Créer un élément */
        post: operations["createBlockItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/blocks/{blockId}/items/order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Réordonner les éléments */
        put: operations["reorderBlockItems"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/blocks/{blockId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
                itemId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Modifier un élément */
        put: operations["updateBlockItem"];
        post?: never;
        /** Supprimer un élément */
        delete: operations["deleteBlockItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lire le thème */
        get: operations["getTheme"];
        /** Enregistrer le brouillon de thème */
        put: operations["saveThemeDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/theme/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publie le brouillon et rend la page visible */
        post: operations["publishTheme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/theme/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les presets */
        get: operations["listThemePresets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/uploads/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signer un upload Cloudinary */
        post: operations["signUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enregistre un asset Cloudinary après upload (vérifie la signature de la réponse Cloudinary) */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/uploads/local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload direct (dev / sans Cloudinary). Désactivé si `LOCAL_UPLOADS_ENABLED=false`. */
        post: operations["uploadLocal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
            };
            cookie?: never;
        };
        /** Page publique */
        get: operations["getPublicPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{handle}/blocks/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
                slug: string;
            };
            cookie?: never;
        };
        /** Détail d'un bloc public */
        get: operations["getPublicBlock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{handle}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enregistrer un événement analytics */
        post: operations["trackEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{handle}/contact": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Envoyer un message au créateur */
        post: operations["sendContactMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{handle}/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        /** Fiche produit publique */
        get: operations["getPublicProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{handle}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Créer une commande */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/orders/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statut public d'une commande */
        get: operations["getOrderStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister mes produits */
        get: operations["listProducts"];
        put?: never;
        /** Créer un produit */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Modifier un produit */
        put: operations["updateProduct"];
        post?: never;
        /** Suppression logique (les commandes restent) */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister mes commandes */
        get: operations["listOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mes gains */
        get: operations["getEarnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Messages reçus */
        get: operations["listContactMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistiques de trafic */
        get: operations["getAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook fournisseur de paiement */
        post: operations["paymentWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/mock/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page de paiement simulée (profil dev/test uniquement) */
        get: operations["mockPaymentPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/mock/{reference}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simuler l'issue d'un paiement (mock) */
        post: operations["mockPaymentComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
            /** @description Code machine stable (ex. HANDLE_TAKEN) */
            code?: string;
            errors?: {
                field: string;
                message: string;
            }[];
        };
        Handle: string;
        HexColor: string;
        Unit: number;
        /** @description Schémas autorisés — https:, mailto:, tel:, https://wa.me/ */
        SafeUrl: string;
        PageMeta: {
            page: number;
            size: number;
            /** Format: int64 */
            totalElements: number;
            totalPages: number;
        };
        OrderRequest: {
            ids: string[];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            handle: components["schemas"]["Handle"];
            displayName: string;
            /** @constant */
            acceptTerms: true;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            password: string;
        };
        /** @enum {string} */
        Plan: "free" | "pro";
        Me: {
            /** Format: uuid */
            id: string;
            email: string;
            handle: string;
            displayName: string;
            plan: components["schemas"]["Plan"];
            published: boolean;
            onboardingCompleted: boolean;
        };
        /** @enum {string} */
        AssetKind: "background" | "thumbnail" | "product" | "item";
        Image: {
            id: string;
            /** @description URL contenant éventuellement `{w}` (largeur demandée). Ex. Cloudinary `…/f_auto,q_auto,c_fill,w_{w}/id` */
            urlTemplate: string;
            /** @description Largeurs disponibles (sinon libres) */
            widths?: number[];
            width?: number;
            height?: number;
            /** @description Couleur dominante hex ou data-URI floue (≤ 1 Ko) */
            placeholder?: string;
        };
        UploadSignature: {
            uploadUrl: string;
            apiKey: string;
            /** Format: int64 */
            timestamp: number;
            signature: string;
            folder: string;
            allowedFormats: string;
            maxBytes: number;
        };
        UploadCompleteRequest: {
            kind: components["schemas"]["AssetKind"];
            publicId: string;
            /** Format: int64 */
            version: number;
            signature: string;
            width: number;
            height: number;
            format: string;
            bytes: number;
        };
        Category: string;
        Profile: {
            handle: string;
            displayName: string;
            taglineLines: string[];
            categories: components["schemas"]["Category"][];
            bio: string;
            backgroundImageId?: string | null;
            backgroundImage?: components["schemas"]["Image"] | null;
            published: boolean;
            plan: components["schemas"]["Plan"];
            onboardingCompleted?: boolean;
        };
        ProfileUpdate: {
            displayName: string;
            taglineLines: string[];
            categories: components["schemas"]["Category"][];
            bio: string;
            backgroundImageId?: string | null;
            published?: boolean;
            onboardingCompleted?: boolean;
        };
        /** @enum {string} */
        SocialPlatform: "tiktok" | "instagram" | "youtube" | "snapchat" | "x" | "facebook" | "linkedin" | "twitch" | "spotify" | "whatsapp";
        SocialAccountInput: {
            platform: components["schemas"]["SocialPlatform"];
            url: components["schemas"]["SafeUrl"];
            /** Format: int64 */
            followersCount: number;
        };
        SocialAccount: components["schemas"]["SocialAccountInput"] & {
            /** Format: uuid */
            id: string;
            position: number;
            /** Format: date-time */
            updatedAt: string;
        };
        ProfileStatsInput: {
            /** Format: int64 */
            followers: number;
            /** Format: int64 */
            likes: number;
            /** Format: int64 */
            views30d: number;
        };
        ProfileStats: components["schemas"]["ProfileStatsInput"] & {
            /** Format: date-time */
            updatedAt?: string | null;
        };
        /** @enum {string} */
        BlockType: "travel" | "shop" | "music" | "content" | "contact" | "link";
        /** @enum {string} */
        BlockIcon: "plane" | "shopping-bag" | "music" | "clapperboard" | "mail" | "link" | "camera" | "heart" | "star" | "map-pin" | "mic" | "gamepad" | "book" | "briefcase";
        BlockInput: {
            type: components["schemas"]["BlockType"];
            title: string;
            subtitle?: string;
            icon?: components["schemas"]["BlockIcon"];
            thumbnailImageId?: string | null;
            /** @description Obligatoire pour `link` */
            url?: components["schemas"]["SafeUrl"] | null;
            /** @default true */
            visible: boolean;
            config?: components["schemas"]["BlockConfig"];
        };
        /** @description Options propres au type (contact → canaux) */
        BlockConfig: {
            whatsapp?: string;
            /** Format: email */
            email?: string;
            phone?: string;
        };
        Block: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["BlockType"];
            slug: string;
            title: string;
            subtitle?: string;
            icon?: components["schemas"]["BlockIcon"];
            thumbnailImageId?: string | null;
            thumbnail?: components["schemas"]["Image"] | null;
            url?: string | null;
            position: number;
            visible: boolean;
            config?: components["schemas"]["BlockConfig"];
            itemCount?: number;
        };
        BlockItemInput: {
            title: string;
            description?: string;
            url?: components["schemas"]["SafeUrl"] | null;
            imageId?: string | null;
        };
        BlockItem: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            url?: string | null;
            imageId?: string | null;
            image?: components["schemas"]["Image"] | null;
            embed?: components["schemas"]["Embed"] | null;
            position: number;
        };
        Embed: {
            /** @enum {string} */
            provider: "youtube" | "spotify";
            /** @description URL d'intégration (youtube-nocookie / open.spotify.com/embed) */
            src: string;
        };
        ThemeConfig: {
            /** @constant */
            version: 1;
            preset: components["schemas"]["ThemePresetId"];
            colors: {
                accent: components["schemas"]["HexColor"];
                text: components["schemas"]["HexColor"];
                textMuted: components["schemas"]["HexColor"];
                cardBg: components["schemas"]["HexColor"];
                cardBgOpacity: components["schemas"]["Unit"];
                cardBorder: components["schemas"]["HexColor"];
                cardBorderOpacity: components["schemas"]["Unit"];
                overlay: components["schemas"]["HexColor"];
                overlayStrength: components["schemas"]["Unit"];
                statGlow: components["schemas"]["HexColor"];
            };
            background: {
                /** @enum {string} */
                type: "image" | "gradient" | "solid";
                imageId?: string | null;
                color?: components["schemas"]["HexColor"];
                gradientFrom?: components["schemas"]["HexColor"];
                gradientTo?: components["schemas"]["HexColor"];
                gradientAngle?: number;
                focal: {
                    x: components["schemas"]["Unit"];
                    y: components["schemas"]["Unit"];
                };
                blur: number;
            };
            typography: {
                /** @enum {string} */
                display: "kaushan-script" | "yellowtail" | "marck-script" | "caveat-brush";
                /** @enum {string} */
                hand: "caveat" | "reenie-beanie";
                /** @enum {string} */
                body: "inter" | "system";
                nameScale: number;
            };
            cards: {
                /** @enum {string} */
                style: "glass" | "solid" | "outline";
                radius: number;
                showThumbnail: boolean;
                /** @enum {string} */
                thumbnailSide: "left" | "right";
                /** @enum {string} */
                density: "compact" | "comfortable";
                blur: number;
            };
            social: {
                /** @enum {string} */
                position: "right" | "left" | "below-stats";
                showCounts: boolean;
                /** @enum {string} */
                shape: "circle" | "rounded" | "square";
            };
            layout: {
                showTagline: boolean;
                showCrown: boolean;
                showStats: boolean;
                showCategories: boolean;
                footerText: string;
            };
            motion: {
                enabled: boolean;
            };
        };
        /** @enum {string} */
        ThemePresetId: "sunset" | "midnight-blue" | "emerald-night" | "rose-gold" | "clean-light" | "custom";
        ThemePreset: {
            id: components["schemas"]["ThemePresetId"];
            name: string;
            config: components["schemas"]["ThemeConfig"];
        };
        ThemeState: {
            draft: components["schemas"]["ThemeConfig"];
            published?: components["schemas"]["ThemeConfig"] | null;
            version: number;
            hasUnpublishedChanges: boolean;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            publishedAt?: string | null;
        };
        PublicProfile: {
            handle: string;
            displayName: string;
            taglineLines: string[];
            categories: string[];
            bio: string;
        };
        PublicPage: {
            profile: components["schemas"]["PublicProfile"];
            stats?: components["schemas"]["ProfileStats"] | null;
            socials: {
                platform: components["schemas"]["SocialPlatform"];
                url: string;
                /** Format: int64 */
                followersCount: number;
            }[];
            blocks: components["schemas"]["Block"][];
            theme: components["schemas"]["ThemeConfig"];
            /** @description Toutes les images référencées (fond, vignettes), indexées par id */
            images: {
                [key: string]: components["schemas"]["Image"];
            };
            /** @description false pour le plan Pro */
            showBranding: boolean;
            preview: boolean;
            seo?: {
                title?: string;
                description?: string;
                ogImage?: string;
            };
        };
        PublicBlockDetail: {
            block: components["schemas"]["Block"];
            items: components["schemas"]["BlockItem"][];
            products: components["schemas"]["PublicProduct"][];
        };
        AnalyticsEventInput: {
            /** @enum {string} */
            type: "page_view" | "link_click";
            /** Format: uuid */
            blockId?: string | null;
            /** @description Ex. social:tiktok, block, mylinks */
            target?: string;
            referrer?: string;
        };
        ContactMessageInput: {
            name: string;
            /** Format: email */
            email?: string;
            phone?: string;
            message: string;
            /** @description Pot de miel anti-spam (doit rester vide) */
            website?: string;
        };
        ContactMessage: {
            /** Format: uuid */
            id: string;
            name: string;
            email?: string | null;
            phone?: string | null;
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        ContactMessagePage: {
            items: components["schemas"]["ContactMessage"][];
            page: components["schemas"]["PageMeta"];
        };
        ProductInput: {
            title: string;
            /** Format: int64 */
            priceXof: number;
            description?: string;
            stock?: number | null;
            active: boolean;
            imageIds: string[];
        };
        Product: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: int64 */
            priceXof: number;
            description?: string;
            stock?: number | null;
            active: boolean;
            imageIds: string[];
            images: components["schemas"]["Image"][];
            /** Format: date-time */
            createdAt: string;
        };
        PublicProduct: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: int64 */
            priceXof: number;
            description?: string;
            images: components["schemas"]["Image"][];
            available: boolean;
        };
        /** @enum {string} */
        PaymentProviderId: "mock" | "paydunya" | "cinetpay";
        CheckoutRequest: {
            /** Format: uuid */
            productId: string;
            quantity: number;
            buyerName: string;
            buyerPhone: string;
            /** Format: email */
            buyerEmail?: string;
            provider?: components["schemas"]["PaymentProviderId"];
            /** @description Clé générée par le client pour éviter les doubles commandes */
            idempotencyKey?: string;
        };
        CheckoutResponse: {
            reference: string;
            paymentUrl: string;
            status: components["schemas"]["OrderStatus"];
            /** Format: int64 */
            amountXof: number;
        };
        /** @enum {string} */
        OrderStatus: "PENDING" | "PAID" | "FAILED" | "CANCELED";
        OrderStatusView: {
            reference: string;
            status: components["schemas"]["OrderStatus"];
            /** Format: int64 */
            amountXof: number;
            productTitle: string;
            quantity?: number;
            creatorHandle: string;
            creatorName: string;
            /** Format: date-time */
            paidAt?: string | null;
        };
        Order: {
            /** Format: uuid */
            id: string;
            reference: string;
            status: components["schemas"]["OrderStatus"];
            /** Format: int64 */
            amountXof: number;
            /** Format: int64 */
            commissionXof: number;
            /** Format: int64 */
            netXof: number;
            provider: components["schemas"]["PaymentProviderId"];
            productTitle: string;
            quantity: number;
            buyerName: string;
            buyerPhone: string;
            buyerEmail?: string | null;
            /** @enum {string} */
            payoutStatus?: "NONE" | "PENDING_PAYOUT" | "PAID_OUT";
            needsAttention?: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            paidAt?: string | null;
        };
        OrderPage: {
            items: components["schemas"]["Order"][];
            page: components["schemas"]["PageMeta"];
        };
        Earnings: {
            /** Format: int64 */
            grossXof: number;
            /** Format: int64 */
            commissionXof: number;
            /** Format: int64 */
            netXof: number;
            /** Format: int64 */
            pendingPayoutXof: number;
            /** Format: int64 */
            paidOutXof: number;
            paidOrders: number;
            commissionPercent: number;
            last30Days: {
                /** Format: date */
                date: string;
                /** Format: int64 */
                netXof: number;
                orders: number;
            }[];
        };
        AnalyticsSummary: {
            days: number;
            /** Format: int64 */
            pageViews: number;
            /** Format: int64 */
            uniqueVisitors?: number;
            /** Format: int64 */
            clicks: number;
            byDay: {
                /** Format: date */
                date: string;
                /** Format: int64 */
                pageViews: number;
                /** Format: int64 */
                clicks: number;
            }[];
            byBlock: {
                blockId?: string | null;
                target: string;
                title?: string;
                /** Format: int64 */
                clicks: number;
            }[];
        };
    };
    responses: {
        /** @description Erreur RFC 7807 */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        HandlePath: components["schemas"]["Handle"];
        BlockId: string;
        ProductId: string;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cookie posé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Compte créé et session ouverte */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session ouverte */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session fermée */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Email envoyé si le compte existe (réponse identique sinon) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["Problem"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Mot de passe modifié */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
        };
    };
    checkHandle: {
        parameters: {
            query: {
                handle: components["schemas"]["Handle"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disponibilité */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        handle: string;
                        available: boolean;
                        /** @enum {string} */
                        reason?: "taken" | "reserved" | "invalid";
                    };
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Utilisateur courant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Compte supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Profil mis à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    getSocials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Réseaux */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccount"][];
                };
            };
        };
    };
    updateSocials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    items: components["schemas"]["SocialAccountInput"][];
                };
            };
        };
        responses: {
            /** @description Réseaux remplacés */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccount"][];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stats déclaratives */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileStats"];
                };
            };
        };
    };
    updateStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileStatsInput"];
            };
        };
        responses: {
            /** @description Stats mises à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileStats"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    getPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPage"];
                };
            };
        };
    };
    listBlocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Blocs triés */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"][];
                };
            };
        };
    };
    createBlock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockInput"];
            };
        };
        responses: {
            /** @description Bloc créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    reorderBlocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Nouvel ordre */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"][];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    updateBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockInput"];
            };
        };
        responses: {
            /** @description Bloc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    deleteBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    listBlockItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Éléments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockItem"][];
                };
            };
        };
    };
    createBlockItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockItemInput"];
            };
        };
        responses: {
            /** @description Élément créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockItem"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    reorderBlockItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Nouvel ordre */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockItem"][];
                };
            };
        };
    };
    updateBlockItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockItemInput"];
            };
        };
        responses: {
            /** @description Élément */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockItem"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteBlockItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockId: components["parameters"]["BlockId"];
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brouillon et version publiée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeState"];
                };
            };
        };
    };
    saveThemeDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThemeConfig"];
            };
        };
        responses: {
            /** @description Brouillon enregistré */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeState"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    publishTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeState"];
                };
            };
        };
    };
    listThemePresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemePreset"][];
                };
            };
        };
    };
    signUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    kind: components["schemas"]["AssetKind"];
                };
            };
        };
        responses: {
            /** @description Paramètres d'upload signé Cloudinary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSignature"];
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadCompleteRequest"];
            };
        };
        responses: {
            /** @description Asset */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    uploadLocal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    kind: components["schemas"]["AssetKind"];
                };
            };
        };
        responses: {
            /** @description Asset */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            400: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
        };
    };
    getPublicPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page publiée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPage"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getPublicBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Détail du bloc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBlockDetail"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    trackEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticsEventInput"];
                "text/plain": string;
            };
        };
        responses: {
            /** @description Accepté */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["Problem"];
        };
    };
    sendContactMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactMessageInput"];
            };
        };
        responses: {
            /** @description Message transmis */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    getPublicProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fiche produit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProduct"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: components["parameters"]["HandlePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Commande créée, redirection vers le paiement */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    getOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statut (page de confirmation) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusView"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Produit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOrders: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                status?: components["schemas"]["OrderStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commandes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPage"];
                };
            };
        };
    };
    getEarnings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gains */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Earnings"];
                };
            };
        };
    };
    listContactMessages: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages reçus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactMessagePage"];
                };
            };
        };
    };
    getAnalytics: {
        parameters: {
            query?: {
                days?: 7 | 30;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trafic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
        };
    };
    paymentWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["PaymentProviderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Traité (ou déjà traité — idempotent) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    mockPaymentPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page HTML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    mockPaymentComplete: {
        parameters: {
            query: {
                outcome: "success" | "failure" | "cancel";
            };
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirection vers la page de confirmation */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
